### ISSUE TITLE
/sys/fs/pstore idempotency issues

### ISSUE THREAD

**Issue by ghost** [redispade/device_xiaomi_grus-twrp#2]
Hi @redispade

I use your latest 11th build, works great, thanks :D 
But /sys/fs/pstore gets overwritten by the twrp's kernel, which is should not be since the system's (android) kernel are storing logs on it.

### Suggestion
Disabling `CONFIG_PSTORE_CONSOLE` and `CONFIG_PSTORE_PMSG` should resolve this issues.
References : https://github.com/wight554/chiron/commit/2eaa213851e89b9dddc3f85ad6452e98ae621c6f

Regards, Nanda Oktavera

**Comment by redispade** [comment]
It is like that since 10 September, Kowalski kernel repository fork, commit 0a94adfea71d72c43e58d37ca6a6642ef4fc271e

**Comment by redispade** [comment]
https://github.com/redispade/kowalski-grus/commit/0a94adfea71d72c43e58d37ca6a6642ef4fc271e

**Comment by ghost** [comment]
I had to run my own build before because I look at the /proc/config.gz and both `CONFIG_PSTORE_CONSOLE` and `CONFIG_PSTORE_PMSG` are still enabled, so funny that I'm looking at faked config the whole time.

Thank you for clarifying, have a good day.
